import Foundation
import Libavcodec
import Testing
@testable import AetherEngine

@Suite("Issue 191: exact IRAP seek")
struct Issue191IRAPSeekTests {

    @Test("seeking to an indexed IRAP lands on that IRAP")
    func indexedIRAPLanding() throws {
        let data = try #require(
            Data(base64Encoded: Self.fixtureBase64, options: .ignoreUnknownCharacters)
        )
        let demuxer = Demuxer()
        try demuxer.open(reader: DataIOReader(data: data), formatHint: "mp4")
        defer { demuxer.close() }

        let videoIndex = demuxer.videoStreamIndex
        let targetPTS = try #require(
            demuxer.indexedKeyframes(streamIndex: videoIndex).sorted().dropFirst().first
        )

        #expect(demuxer.seek(to: targetPTS, streamIndex: videoIndex))

        var firstVideoDTS: Int64?
        var firstVideoIsKey = false
        while firstVideoDTS == nil, let packet = try demuxer.readPacket() {
            if packet.pointee.stream_index == videoIndex {
                firstVideoDTS = packet.pointee.dts
                firstVideoIsKey = (packet.pointee.flags & AV_PKT_FLAG_KEY) != 0
            }
            var packetToFree: UnsafeMutablePointer<AVPacket>? = packet
            trackedPacketFree(&packetToFree)
        }
        #expect(firstVideoIsKey)
        #expect(firstVideoDTS == targetPTS)
    }

    private static let fixtureBase64 = """
        AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAutbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAAD6AAAQAA
        AQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAwAAB5p0cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAD6AAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAA
        AAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAEAAAABAAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAA+gAAAdTAABAAAAAAcS
        bWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAFfkAAFfkBVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRl
        b0hhbmRsZXIAAAAGvW1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAA
        AQAABn1zdGJsAAAAvXN0c2QAAAAAAAAAAQAAAK1hdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAEAAQABIAAAASAAAAAAA
        AAABFUxhdmM2Mi4yOC4xMDEgbGlieDI2NAAAAAAAAAAAAAAAGP//AAAAM2F2Y0MBZAAK/+EAGGdkAAqs2UQmwEQAAAMABAAA
        AwDAPEiWWAEABGjvj8v9+PgAAAAAEHBhc3AAAAABAAAAAQAAABRidHJ0AAAAAAAAEBAAAAAAAAAAGHN0dHMAAAAAAAAAAQAA
        AGAAAA6mAAAAHHN0c3MAAAAAAAAAAwAAAAEAAAAwAAAAXwAAAwhjdHRzAAAAAAAAAF8AAAABAAAdTAAAAAEAAEk+AAAAAQAA
        HUwAAAABAAAAAAAAAAEAAA6mAAAAAQAAST4AAAABAAAdTAAAAAEAAAAAAAAAAQAADqYAAAABAABJPgAAAAEAAB1MAAAAAQAA
        AAAAAAABAAAOpgAAAAEAAEk+AAAAAQAAHUwAAAABAAAAAAAAAAEAAA6mAAAAAQAAST4AAAABAAAdTAAAAAEAAAAAAAAAAQAA
        DqYAAAABAABJPgAAAAEAAB1MAAAAAQAAAAAAAAABAAAOpgAAAAEAAEk+AAAAAQAAHUwAAAABAAAAAAAAAAEAAA6mAAAAAQAA
        ST4AAAABAAAdTAAAAAEAAAAAAAAAAQAADqYAAAABAABJPgAAAAEAAB1MAAAAAQAAAAAAAAABAAAOpgAAAAEAAEk+AAAAAQAA
        HUwAAAABAAAAAAAAAAEAAA6mAAAAAQAAST4AAAABAAAdTAAAAAEAAAAAAAAAAQAADqYAAAABAAAr8gAAAAEAAA6mAAAAAQAA
        HUwAAAABAABJPgAAAAEAAB1MAAAAAQAAAAAAAAABAAAOpgAAAAEAAEk+AAAAAQAAHUwAAAABAAAAAAAAAAEAAA6mAAAAAQAA
        ST4AAAABAAAdTAAAAAEAAAAAAAAAAQAADqYAAAABAABJPgAAAAEAAB1MAAAAAQAAAAAAAAABAAAOpgAAAAEAAEk+AAAAAQAA
        HUwAAAABAAAAAAAAAAEAAA6mAAAAAQAAST4AAAABAAAdTAAAAAEAAAAAAAAAAQAADqYAAAABAABJPgAAAAEAAB1MAAAAAQAA
        AAAAAAABAAAOpgAAAAEAAEk+AAAAAQAAHUwAAAABAAAAAAAAAAEAAA6mAAAAAQAAST4AAAABAAAdTAAAAAEAAAAAAAAAAQAA
        DqYAAAABAABJPgAAAAEAAB1MAAAAAQAAAAAAAAABAAAOpgAAAAEAAEk+AAAAAQAAHUwAAAABAAAAAAAAAAEAAA6mAAAAAQAA
        K/IAAAABAAAOpgAAAAIAAB1MAAAAWHN0c2MAAAAAAAAABgAAAAEAAAADAAAAAQAAAA8AAAAEAAAAAQAAABAAAAADAAAAAQAA
        AB0AAAAEAAAAAQAAAB4AAAADAAAAAQAAACAAAAABAAAAAQAAAZRzdHN6AAAAAAAAAAAAAABgAAAC3QAAAA4AAAAMAAAADAAA
        AAwAAAAPAAAADgAAAAwAAAAMAAAADwAAAA4AAAAMAAAADAAAAA8AAAAOAAAADAAAAAwAAAAPAAAADgAAAAwAAAAMAAAADwAA
        AA4AAAAMAAAADAAAAA8AAAAOAAAADAAAAAwAAAAPAAAADgAAAAwAAAAMAAAADwAAAA4AAAAMAAAADAAAAA8AAAAOAAAADAAA
        AAwAAAAPAAAADgAAAAwAAAAMAAAAEAAAAAwAAAAvAAAADgAAAAwAAAAMAAAADAAAAA8AAAAOAAAADAAAAAwAAAAPAAAADgAA
        AAwAAAAMAAAADwAAAA4AAAAMAAAADAAAAA8AAAAOAAAADAAAAAwAAAAPAAAADgAAAAwAAAAMAAAADwAAAA4AAAAMAAAADAAA
        AA8AAAAOAAAADAAAAAwAAAAPAAAADgAAAAwAAAAMAAAADwAAAA4AAAAMAAAADAAAAA8AAAAOAAAADAAAAAwAAAAQAAAADAAA
        AC4AAAAOAAAAkHN0Y28AAAAAAAAAIAAADMwAABCZAAAROQAAEcQAABJSAAAS3gAAE2wAABP1AAAUiQAAFRQAABWfAAAWLgAA
        Fr0AABdPAAAX5QAAGIoAABk5AAAZxQAAGlwAABruAAAbewAAHBAAAByxAAAdUgAAHe4AAB6QAAAfNwAAH+0AACCTAAAhQQAA
        Ih4AACMYAAADPXRyYWsAAABcdGtoZAAAAAMAAAAAAAAAAAAAAAIAAAAAAAAPoAAAAAAAAAAAAAAAAQEAAAAAAQAAAAAAAAAA
        AAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAACRlZHRzAAAAHGVsc3QAAAAAAAAAAQAAD6AAAAQAAAEAAAAA
        ArVtZGlhAAAAIG1kaGQAAAAAAAAAAAAAAAAAAB9AAACBAFXEAAAAAAAtaGRscgAAAAAAAAAAc291bgAAAAAAAAAAAAAAAFNv
        dW5kSGFuZGxlcgAAAAJgbWluZgAAABBzbWhkAAAAAAAAAAAAAAAkZGluZgAAABxkcmVmAAAAAAAAAAEAAAAMdXJsIAAAAAEA
        AAIkc3RibAAAAH5zdHNkAAAAAAAAAAEAAABubXA0YQAAAAAAAAABAAAAAAAAAAAAAQAQAAAAAB9AAAAAAAA2ZXNkcwAAAAAD
        gICAJQACAASAgIAXQBUAAAAAAB9AAAAdmQWAgIAFFYhW5QAGgICAAQIAAAAUYnRydAAAAAAAAB9AAAAdmQAAACBzdHRzAAAA
        AAAAAAIAAAAgAAAEAAAAAAEAAAEAAAAAHHN0c2MAAAAAAAAAAQAAAAEAAAABAAAAAQAAAJhzdHN6AAAAAAAAAAAAAAAhAAAA
        7wAAANYAAAB5AAAAZQAAAGUAAABjAAAAZwAAAGMAAABrAAAAYgAAAGQAAABpAAAAZgAAAGkAAABvAAAAbwAAAGYAAABoAAAA
        bgAAAGkAAABmAAAAbwAAAHgAAAB4AAAAdQAAAHwAAAB+AAAAjQAAAH8AAAB5AAAAtwAAALAAAAAFAAAAlHN0Y28AAAAAAAAA
        IQAAC90AAA/DAAAQwAAAEV8AABHtAAASewAAEwUAABOSAAAUHgAAFLIAABU7AAAVxQAAFlcAABbmAAAXdgAAGBsAABjTAAAZ
        XQAAGe4AABqFAAAbFQAAG6EAABw5AAAc2gAAHXkAAB4UAAAeuQAAH2AAACAUAAAgyAAAIWcAACJoAAAjJgAAABpzZ3BkAQAA
        AHJvbGwAAAACAAAAAf//AAAAHHNiZ3AAAAAAcm9sbAAAAAEAAAAhAAAAAQAAAGJ1ZHRhAAAAWm1ldGEAAAAAAAAAIWhkbHIA
        AAAAAAAAAG1kaXJhcHBsAAAAAAAAAAAAAAAALWlsc3QAAAAlqXRvbwAAAB1kYXRhAAAAAQAAAABMYXZmNjIuMTIuMTAxAAAA
        CGZyZWUAABdWbWRhdN4CAExhdmM2Mi4yOC4xMDEAAjilUtNG7rP2j7fElXctEiRIkSSDatp2radq2nauM7Vxnatpnp2xTtis
        O1bTtXGdq4zlWU5VtOVbTYsTjsTlWUhAhAhAhElGSjKoyqUyVpTXXK6u7cwN2KUCUDAwMDAxs3LLLLLLKblllllllNyyyyyy
        yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
        yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy8AAACqwYF//+n3EXpvebZSLeWLNgg2SPu73gyNjQgLSBjb3Jl
        IDE2NSByMzIyMiBiMzU2MDVhIC0gSC4yNjQvTVBFRy00IEFWQyBjb2RlYyAtIENvcHlsZWZ0IDIwMDMtMjAyNSAtIGh0dHA6
        Ly93d3cudmlkZW9sYW4ub3JnL3gyNjQuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTEgcmVmPTEgZGVibG9jaz0xOjA6MCBhbmFs
        eXNlPTB4MzoweDExMyBtZT1oZXggc3VibWU9MiBwc3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0wIG1lX3Jhbmdl
        PTE2IGNocm9tYV9tZT0xIHRyZWxsaXM9MCA4eDhkY3Q9MSBjcW09MCBkZWFkem9uZT0yMSwxMSBmYXN0X3Bza2lwPTEgY2hy
        b21hX3FwX29mZnNldD0wIHRocmVhZHM9MiBsb29rYWhlYWRfdGhyZWFkcz0xIHNsaWNlZF90aHJlYWRzPTAgbnI9MCBkZWNp
        bWF0ZT0xIGludGVybGFjZWQ9MCBibHVyYXlfY29tcGF0PTAgY29uc3RyYWluZWRfaW50cmE9MCBiZnJhbWVzPTMgYl9weXJh
        bWlkPTIgYl9hZGFwdD0xIGJfYmlhcz0wIGRpcmVjdD0xIHdlaWdodGI9MSBvcGVuX2dvcD0wIHdlaWdodHA9MSBrZXlpbnQ9
        NDcga2V5aW50X21pbj0yNCBzY2VuZWN1dD0wIGludHJhX3JlZnJlc2g9MCByY19sb29rYWhlYWQ9MTAgcmM9Y3JmIG1idHJl
        ZT0xIGNyZj0yMy4wIHFjb21wPTAuNjAgcXBtaW49MCBxcG1heD02OSBxcHN0ZXA9NCBpcF9yYXRpbz0xLjQwIGFxPTE6MS4w
        MACAAAAAKmWIhAA7/9n8D4Hjd1trA/mOdmRChSeXdwuqCyQ6zNqRbPukzHnuF10z8QAAAApBmiQYhv/+p4+IAAAACEGeQkIX
        /wm5AQCc2TkdRLoZRLwVZL59vn/+L/z/XrjjWrSf9P0//D/z/HnjrV3dZ/0/P/p/8/XXHGtWa/9Pz/6f/f644441LxZdFIHA
        ZdHJOJpmbDFc00y9jY2R2bNkSxyH68F2CBwlGE6znRVUYxqDR0UR0G6B1Cg3QadVFBxGrYiLNhHy3LdsnQuja+xsii2FL8iR
        wVlzLOdiPPOc51KVGpSp555551TqnVOqeeedSp51TzqnnnnVOrYeeeeegoLqUInNYUidw/BTnVDzT8yp5+af5fKrmIn6joUg
        DgAAAAgBnmFEK/8MOAAAAAgBnmNEK/8MOQAAAAtBmmg0TEN//qePiQES8ori5mN889/n/p/9utccXq5Ll1qRMt31zdAe5B/4
        Az+4f+MwHvoB/gB0J9wQ9/fRCB8AO+4D/wYO+5B/4bDvvCD/DYHuQPmzAe+gD4zCz30GEl/Dqfx8OJ/DAp/HwkvEYomWCIAx
        gCQYgAiEQACwVCwbYhESmA4AAAAKQZ6GRREsL/8JuQAAAAgBnqVEK/8MOQAAAAgBnqdEK/8MOAEEMofmf5/j78+r7/T//l//
        xnGu/r34+P03x7fbXP7+HesrVbwFf+796im/fYJKb1N5SmhTfv33b999+/few3t9yoS92/fvoCAXDUFgqFgxBKAAzACYAqEg
        AiEABMOAbQBQAIAOAAAAC0GarDRMQ3/+p4+IAAAACkGeykUVLC//CbkAAAAIAZ7pRCv/DDgA/jKEIBFCEG6/x7zff6f/6P/5
        Zxx49vHXn7TNevr7fF73Urz41gKsp6f7Yg/Lln/sz+kkwk4GBgbuBsGQMDA2LBULBLkKBS4TCYWC4VAEoAC4AmALBQJBIFwg
        AJhYLBngERS4DgAAAAgBnutEK/8MOAAAAAtBmvA0TEN//qePiQAAAApBnw5FFSwv/wm5AP4yh+Z/P9f1+2Tfr//D//PNcePv
        615+eeuvtx37fj81G5lYC/q2bFWzZskFIrNmxs6IN2zZs2NkfVs2bNlhs2bNhUKRFARC4aAsFgsAJBSAYQBYAZwzgCQIgAEw
        qAJABEBwAAAACAGfLUQr/ww5AAAACAGfL0Qr/ww4AAAAC0GbNDRMQ3/+p4+IAPwyh+Z+v6fXz489/p//y//46nGeffrr7aX6
        8+vPx9l013eAyQ3721TfvoFG/evvKUupv379+/fe+/fv32G/y795YKQFAlMJhcLBYKgCURSIQC4WAFAsFIiUAgALhMKhlC0Q
        iJTAcAAAAApBn1JFFSwv/wm5AAAACAGfcUQr/ww4AAAACAGfc0Qr/ww4AQIyh+Z+Pf8fOZX2//1//z3rXf19uPPrvzO/Pjzf
        jJrn29VgLQEldWqoVgPz/sdUX4/21eDVq1aoatWrVMav7atRUJQFAQDAEwyBjDaAJRAEQBcAWDEFAQC4TAEwsAKABABwAAAA
        C0GbeDRMQ3/+p4+JAAAACkGflkUVLC//CbgAAAAIAZ+1RCv/DDkBADKH5n+P4/X58efH2//1f/z6vXj8fnrXcrr547/fw7jN
        JgLeP+X8lXr/l/KwSts/ky+M6IPp/L1ev1bNmx6tmzZMfyjs2FglEUClwiGwLhUJBYMsQBmAFwBUJABAIgCYYw1hlCsAiKXA
        cAAAAAgBn7dEK/8MOQAAAAtBm7w0TEN//qePiAAAAApBn9pFFSwv/wm5AP4yh+Z/j+n49933+n//L//jqcOPfXx+c4nj49/x
        zkbrz4oCfu371jfvoElN7fvKUupv379+/fvb9+/fMb/Lv3lQp2uUBEIBcLhcKBQEQBcLhpAFAoAEAzBMAVCoAkCIRAcAAAAI
        AZ/5RCv/DDgAAAAIAZ/7RCv/DDkAAAALQZvgNExDf/6nj4kA/DKEIBH5D7/Mrx4//w//z3rXP164v1ddfbrn4m92357UDGkr
        q1SCVdWpXU1dUXLVq1aoatU9WrVqmNXXVqLBigKBLCEQ1BcLBIAUiEAwhMKgDKGcJBSAYAuAKhQJBaIREpgOAAAACkGeHkUV
        LC//CbgAAAAIAZ49RCv/DDgAAAAIAZ4/RCv/DDkBAjKFSGGr9/f677rf6f/6P/53HHr8e9/X53qePbx59vtVaplAViMT+X8v
        5bcI2xScPGSZiEJCQl3CSswSEhLWTu4SVCQkqEvprmoCAQCYXCwVAFIhAIACYAqFgkFARAFwqFgoFARCADgAAAALQZokNExD
        f/6nj4gAAAAKQZ5CRRUsL/8JuQAAAAgBnmFEK/8MOAECMofmf6f0/fn8+fH6f/8v/+M101688fm69vz9fPn6/OcM68QCsVFl
        N++qhSm/epvKUwKb9++7evv379+Mb9+8WCWgUCmAIh7AuGMLACgUBEATCobQxAiKAmEQBUKhIKwFIilwHAAAAAgBnmNEK/8M
        OQAAAAtBmmg0TEN//qePiQAAAApBnoZFFSwv/wm5AP4yh+Z/p/T8b8Zv3//wf/zzrXfx489forz4nP1fNTm9c1gL11alWrVq
        +ldRig1NWpqgi5atWrU1atWrVq1VGqGrUYgpy1atVARCAXDSFQqAKQCIZgmHAASCQUCkQgEAmFQqFAkCIRAcAAAACAGepUQr
        /ww5AAAACAGep0Qr/ww4AAAAC0GarDRMQ3/+p4+IAPoyicN37/p9c/PHj9P/+X//HU659vnz7fmnXj2+f58bqla3AAa8/p9A
        cPPfR954BOLzwZzgJTcE/R76PPPMZ9HnnsY169eskFPy169dARCITDSFwsGWIxQAFwuFgBUKBQEQiAJhULBILRCIlhAcAAAA
        CkGeykUVLC//CbkAAAAIAZ7pRCv/DDgAAAAIAZ7rRCv/DDgAAAAMQZruNEyiYX/+jNNhAQIyhUhBu/0/j+fnx16/T/+///11
        rXPx9v1r7VPr86z43W645873gLQFm/y/1kEt/l/qp/UowKAYGDAy8GBiQMDC16o/r+H4byjfv3/LAKAgEA9QVCwZwoCAAwgC
        4AsGcAIhMLhYNIeMKBQEQgA4AAAACAGfDUQr/ww5AAAAK2WIggAEf+J/Bd76Rc4kgH9t174HfPC3e8aeaS1BdYN2MXetyWHV
        nRJIyR0AAAAKQZokGIb//qePiAECMofmfv+37+549f/4f/59a14+/zx9fpV337ePjfLWJzqgWgKtWrVQJV1amqrV+6Llq1at
        WrVqatWrVUaoatRIJV1atVAQCIXCocAoAJQAEABcLBnCwSCUQgALhcKhIMUAiKYAHAAAAAhBnkJCF/8JuAAAAAgBnmFEK/8M
        OQAAAAgBnmNEK/8MOAD8Mofmfz+nx3XPf6f/8v/+Ota3578vUr4/Pt668/N3Wa5rAT8fw1trXr15xr4RlrS1kpTS169evXr1
        y169euo1+PXrKBaIoCIQDUFQxhIASgEAiFw0hYMQYgkEgRC4AuG8KBIEQiA4AAAAC0GaaDRMQ3/+p4+IAAAACkGehkURLC//
        CbkAAAAIAZ6lRCv/DDgA/DKEIBFCEG6fr9vHnx+f/9X/8041v4+X7/xV3zea+vesOvXGAmytn9f62Cmz+v9Wz+pRAgDAxJMs
        MPZhgYem0j+sf6/1JBTb/X+v9aAiEQmFQqFABIKAzBMKgCwSBESBMJgC4WDOGWIpESwgOAAAAAgBnqdEK/8MOQAAAAtBmqw0
        TEN//qePiQAAAApBnspFFSwv/wm4AQAyh+Z/p/T9/fmc+//+D/+a9cd/Hv5eLr6/Pnvjr0ZJlUCvt/n/NVq1fzxBig1K6lea
        Llq1efVq1atWrVq1aRq/nq1FArAUCWYIBsCobwygCUQiFwiGMAVCgUCUAgAJhcJBQKAiEAHAAAAACAGe6UQr/ww5AAAACAGe
        60Qr/ww4AAAAC0Ga8DRMQ3/+p4+JAQAyh+Z+/2+vk8fp//y//4zXTj319fO+J3fP1lc6nfnxeArEWa9euQS669aWslKaWvXr
        1tc569evXpma/Hr1kglLXr10BANAXDGFgqEglEAYQBMKhQM4UBANAQAFwqGcMUAiEAHAAAAACkGfDkUVLC//CbkAAAAIAZ8t
        RCv/DDgAAAAIAZ8vRCv/DDgA+jKEyDkKEG79f0+/vzrn1//Y//93fHfx66rcnn7cePx4ob9u5QNMRJs2bNoSwmmmmSYJA5qf
        HYJD0x6aaaaaaaaa42bNmwoFoigU0BmDwBjCwWCgWiAIBMOAAsFgAgJYQiFwyBtDaEoCkRTQA4AAAAALQZs0NExDf/6nj4kA
        AAAKQZ9SRRUsL/8JuAAAAAgBn3FEK/8MOQD8MokQGQoQbv3/T7++XvP/+X//nU4787fj9l68devvvaryVMACvl8vkHx8vl8k
        AAJq+Xy+Xy+QRMtTdI5X4vMTAwMDAwMDS5gwMDG7hUM4U9H8/5/zoCIXCYTDGFQqFIgCIAsAKhiCQUgEAADIGUM4ZYikRKID
        gAAAAAgBn3NEK/8MOAAAAAtBm3g0TEN//qePiQAAAApBn5ZFFSwv/wm5AP4yiOwrEOn+P6/juZnr/+3//6yarrvqu44+dS9b
        qbvXd0AF6XngsPPPOgPPX87zxkZWXGV91nvN4PbwEQAMjQI0CPXr169ctevXruNbXrNoVgKBLMEwuEwqG0AUiEAzBAMgA2hI
        JBSApoDCEwsFQsG2IpESzAOAAAAACAGftUQr/ww5AAAACAGft0Qr/ww5AAAAC0GbvDRMQ3/+p4+IAQAyhOwnChDu/0/Pt454
        rn//T//+6jfXN/H2Tz78bn19l5LpgLbtmxnbNmygbdmzYgpLPLRLPp9eLD8GCSabj3VTTTHJppptIbVgmE9ra2tqQIBUMIUC
        oZwBIJAqFAqFgyhIERIGIKhQPWDfBcPCgJREsIDgAAAACkGf2kUVLC//CbgAAAAIAZ/5RCv/DDkAAAAIAZ/7RCv/DDgA+jKM
        zCsSEO77/P143dZ//W//86zWdc+Xzda5vL9vFZrdlA0IDM6N0bo0w8JzdnZ2emvFCmYXc7bgMo718cA5d9GBtbAwMDA1gMDE
        s94Na+trGRrVaURIJVCgUDQCwSAEoCUQxBUNMAXDOEglEIBQLBYPWCwZ4CURLGA4AAAAC0Gb4DRMQ3/+p4+IAAAACkGeHkUV
        LC//CbkAAAAIAZ49RCv/DDkA/jKEIBEsCkLDGxiT9fG08f/0v//dm/bue323r49X49q5l5NZVgms169dJjP+Wv0gGgNCmBNC
        nQ6t+3//61hrrLrLs7rLrIWFgy/tr167DXXXrM4U169eugIhcNgcA4BIJBSAAgEAqEw2hYKBSIpcLhcOAawuEwl3RPxgqcAA
        AAAIAZ4/RCv/DDkAAAALQZokNExDf/6nj4gAAAAKQZ5CRRUsL/8JuAD6MoRoSBWFhIc3qExPv7+295xz//n///2xddT3VLle
        fG9Kq7UDHEZ000yfCZ5vLwmmfefvccV+9XaHRTwO8mLgCqrjw41aOFFVFX+aY9NNNN6WDvNg7u8C5ppk0k000gnQKBUPaBoh
        +UGSIQAEQxBohQNUMwSgHdCIUDEAHHkAPYDzIeBES7o7/iBQ4AAAAAgBnmFEK/8MOQAAAAgBnmNEK/8MOAAAAAtBmmg0TEN/
        /qePiAECMoj2MiDUxP8/x+O91df/1v/y15c/Xvx5/Oa9vm8/Hit6ySVAAj+/L5A4nnnWqcCyeecVEhRM1JRczlgUi9iGZm+x
        owA88888/yn+U8889hvb95UJe7fv30BALhqCwVCwYgzwAGYLhMKhiCQSgJRCAAxhwDyhcJBLuiXihU4AAAAKQZ6GRRUsL/8J
        uQAAAAgBnqVEK/8MOAAAAAgBnqdEK/8MOQAAAAtBmqw0TEN//qePiQD6MoQgFDWJiDdPx6rJ3//U//j81rnjfHH2upz7e/m+
        YyvO5QNLwuLAwOJTu5FOBgYHrP+TERpGNojk2O/ShgBIWFjOdYWFhYWFhYWFjgFQsEuQoFLhMJhYN4VAEoBALhAOAVCwUCQS
        iKXCATDgHjDKGeApEU0BM4AAAAAKQZ7KRRUsL/8JuAAAAAgBnulEK/8MOQAAAAgBnutEK/8MOAEWUpD2UpiZVVWb4z/9v/tf
        ji7uS5cXnEqXkqbxoZlEgAMyP/+AFWh4etwAAVaHh7dgAAGLQ8PTjmIHZGEYU5iGYMwZgBDHgAH8T8h3RoymHQsFI2Nra/mY
        /2+xJ+fzMPt9gPn8zD7fYD5/MD7fYD5/Mw+32JPz+Zj/b7AfPrA+32lHz+YWAB8/mY/22kn5/Mx/ttCfKMDw8AOzfQPt9hV8
        /mDsD8QtFFL5hEAWDXEekKhIEQiA4AAAAAxBmu40TKJhf/6M02EAAAAIAZ8NRCv/DDkAAAAqZYiEADv/2fwPgeN3W2sD+Y52
        ZEKFJ5d3C6oLJDrM2pFs+6TMee4XXTPwAQqdsL0VZH6iXwfh6/P/p/7/r1rrWtc67//sc/t+vtxrWrvWv1/7e/9fP1xerkkc
        ui/jAAS88lLyUpvvYVzOWl7lpe5B4PM0h5jz0QeYx64PB57SQ/bGebHpAJi0xWdjc/Ed0Bd0RIZLKkMvlz+h85zxmg0H+A/x
        /gP8f4D/H+A/x/gD/H+P8AH+P8f4/wAH+P8f4iN7y1hkMb4+PH4+Pj4+Pj4+Pj4+Pj4+Pj4+PjgAAAAKQZohGIV//jiNwAEY
        gbRw
        """
}
